#use_frameworks!

platform :ios, '9.0'

target 'PPPhotoAuthorisationTool_Example' do
  pod 'PPPhotoAuthorisationTool', :path => '../'

  target 'PPPhotoAuthorisationTool_Tests' do
    inherit! :search_paths
    
  end
end
